version: 2.1

orbs:
  codacy: codacy/base@10.4.2

workflows:
  version: 2

  compile_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: test
          steps:
            - run:
                name: Run rabbitmq for testing
                command: docker run --user rabbitmq --rm -p 5672:5672 rabbitmq:3
                background: true
            - run:
                name: Wait for rabbit to be ready
                command: |
                  sleep 1;

                  until docker logs $(docker container ls  | grep 'rabbit' | awk '{print $1}') | grep "Time to start RabbitMQ";
                  do
                    echo "Waiting for Rabbitmq to start..."
                    sleep 1;
                  done
            - run:
                name: Run tests
                command: sbt +test
          context: CodacyAWS
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: publish
          steps:
            - run:
                name: Retrieve GPG keys
                command: sbt retrieveGPGKeys
            - run:
                name: Publish to bundle
                command: sbt +publishSigned
            - run:
                name: Release bundle to Sonatype
                command: sbt sonatypeBundleRelease
          context: CodacyAWS
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          context: CodacyAWS
          requires:
            - publish
